package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Abitudinialimentari generated by hbm2java
 */
public class Abitudinialimentari implements java.io.Serializable {

	private Integer idAbitudiniAlimentari;
	private Paziente paziente;
	private int numPastiGiorno;
	private boolean primaColazione;
	private String integratori;
	private String cibiNonGraditi;
	private String preferenzaSchemaDietetico;
	private String note;
	private Set modalitapastofuoris = new HashSet(0);
	private Set assunzionebevandes = new HashSet(0);

	public Abitudinialimentari() {
	}

	public Abitudinialimentari(Paziente paziente, int numPastiGiorno,
			boolean primaColazione) {
		this.paziente = paziente;
		this.numPastiGiorno = numPastiGiorno;
		this.primaColazione = primaColazione;
	}

	public Abitudinialimentari(Paziente paziente, int numPastiGiorno,
			boolean primaColazione, String integratori, String cibiNonGraditi,
			String preferenzaSchemaDietetico, String note,
			Set modalitapastofuoris, Set assunzionebevandes) {
		this.paziente = paziente;
		this.numPastiGiorno = numPastiGiorno;
		this.primaColazione = primaColazione;
		this.integratori = integratori;
		this.cibiNonGraditi = cibiNonGraditi;
		this.preferenzaSchemaDietetico = preferenzaSchemaDietetico;
		this.note = note;
		this.modalitapastofuoris = modalitapastofuoris;
		this.assunzionebevandes = assunzionebevandes;
	}

	public Integer getIdAbitudiniAlimentari() {
		return this.idAbitudiniAlimentari;
	}

	public void setIdAbitudiniAlimentari(Integer idAbitudiniAlimentari) {
		this.idAbitudiniAlimentari = idAbitudiniAlimentari;
	}

	public Paziente getPaziente() {
		return this.paziente;
	}

	public void setPaziente(Paziente paziente) {
		this.paziente = paziente;
	}

	public int getNumPastiGiorno() {
		return this.numPastiGiorno;
	}

	public void setNumPastiGiorno(int numPastiGiorno) {
		this.numPastiGiorno = numPastiGiorno;
	}

	public boolean isPrimaColazione() {
		return this.primaColazione;
	}

	public void setPrimaColazione(boolean primaColazione) {
		this.primaColazione = primaColazione;
	}

	public String getIntegratori() {
		return this.integratori;
	}

	public void setIntegratori(String integratori) {
		this.integratori = integratori;
	}

	public String getCibiNonGraditi() {
		return this.cibiNonGraditi;
	}

	public void setCibiNonGraditi(String cibiNonGraditi) {
		this.cibiNonGraditi = cibiNonGraditi;
	}

	public String getPreferenzaSchemaDietetico() {
		return this.preferenzaSchemaDietetico;
	}

	public void setPreferenzaSchemaDietetico(String preferenzaSchemaDietetico) {
		this.preferenzaSchemaDietetico = preferenzaSchemaDietetico;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set getModalitapastofuoris() {
		return this.modalitapastofuoris;
	}

	public void setModalitapastofuoris(Set modalitapastofuoris) {
		this.modalitapastofuoris = modalitapastofuoris;
	}

	public Set getAssunzionebevandes() {
		return this.assunzionebevandes;
	}

	public void setAssunzionebevandes(Set assunzionebevandes) {
		this.assunzionebevandes = assunzionebevandes;
	}

}
