package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Alimento generated by hbm2java
 */
public class Alimento implements java.io.Serializable {

	private Integer idAlimento;
	private String nome;
	private String tipologia;
	private Integer calorie;
	private Set costituziones = new HashSet(0);
	private Set ricettas = new HashSet(0);

	public Alimento() {
	}

	public Alimento(String nome) {
		this.nome = nome;
	}

	public Alimento(String nome, String tipologia, Integer calorie,
			Set costituziones, Set ricettas) {
		this.nome = nome;
		this.tipologia = tipologia;
		this.calorie = calorie;
		this.costituziones = costituziones;
		this.ricettas = ricettas;
	}

	public Integer getIdAlimento() {
		return this.idAlimento;
	}

	public void setIdAlimento(Integer idAlimento) {
		this.idAlimento = idAlimento;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getTipologia() {
		return this.tipologia;
	}

	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}

	public Integer getCalorie() {
		return this.calorie;
	}

	public void setCalorie(Integer calorie) {
		this.calorie = calorie;
	}

	public Set getCostituziones() {
		return this.costituziones;
	}

	public void setCostituziones(Set costituziones) {
		this.costituziones = costituziones;
	}

	public Set getRicettas() {
		return this.ricettas;
	}

	public void setRicettas(Set ricettas) {
		this.ricettas = ricettas;
	}

}
