package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

/**
 * AssunzionebevandeId generated by hbm2java
 */
public class AssunzionebevandeId implements java.io.Serializable {

	private int idAbitudineAlimentare;
	private int idTipologiaBevanda;

	public AssunzionebevandeId() {
	}

	public AssunzionebevandeId(int idAbitudineAlimentare, int idTipologiaBevanda) {
		this.idAbitudineAlimentare = idAbitudineAlimentare;
		this.idTipologiaBevanda = idTipologiaBevanda;
	}

	public int getIdAbitudineAlimentare() {
		return this.idAbitudineAlimentare;
	}

	public void setIdAbitudineAlimentare(int idAbitudineAlimentare) {
		this.idAbitudineAlimentare = idAbitudineAlimentare;
	}

	public int getIdTipologiaBevanda() {
		return this.idTipologiaBevanda;
	}

	public void setIdTipologiaBevanda(int idTipologiaBevanda) {
		this.idTipologiaBevanda = idTipologiaBevanda;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssunzionebevandeId))
			return false;
		AssunzionebevandeId castOther = (AssunzionebevandeId) other;

		return (this.getIdAbitudineAlimentare() == castOther
				.getIdAbitudineAlimentare())
				&& (this.getIdTipologiaBevanda() == castOther
						.getIdTipologiaBevanda());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAbitudineAlimentare();
		result = 37 * result + this.getIdTipologiaBevanda();
		return result;
	}

}
