package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import common.GenericBean;

/**
 * Dieta generated by hbm2java
 */
public class Dieta extends GenericBean implements java.io.Serializable {

	private Integer idDieta;
	private Specifichedieta specifichedieta;
	private Paziente paziente;
	private Date dataInizio;
	private int durataCiclo;
	private int numRipetizCiclo;
	private String note;
	private String ulterioriConsigli;
	private Set personalizzazionegiornatas = new HashSet(0);

	public Dieta() {
	}

	public Dieta(Specifichedieta specifichedieta, Paziente paziente,
			Date dataInizio, int durataCiclo, int numRipetizCiclo) {
		this.specifichedieta = specifichedieta;
		this.paziente = paziente;
		this.dataInizio = dataInizio;
		this.durataCiclo = durataCiclo;
		this.numRipetizCiclo = numRipetizCiclo;
	}

	public Dieta(Specifichedieta specifichedieta, Paziente paziente,
			Date dataInizio, int durataCiclo, int numRipetizCiclo, String note,
			String ulterioriConsigli, Set personalizzazionegiornatas) {
		this.specifichedieta = specifichedieta;
		this.paziente = paziente;
		this.dataInizio = dataInizio;
		this.durataCiclo = durataCiclo;
		this.numRipetizCiclo = numRipetizCiclo;
		this.note = note;
		this.ulterioriConsigli = ulterioriConsigli;
		this.personalizzazionegiornatas = personalizzazionegiornatas;
	}

	public Integer getIdDieta() {
		return this.idDieta;
	}

	public void setIdDieta(Integer idDieta) {
		this.idDieta = idDieta;
	}

	public Specifichedieta getSpecifichedieta() {
		return this.specifichedieta;
	}

	public void setSpecifichedieta(Specifichedieta specifichedieta) {
		this.specifichedieta = specifichedieta;
	}

	public Paziente getPaziente() {
		return this.paziente;
	}

	public void setPaziente(Paziente paziente) {
		this.paziente = paziente;
	}

	public Date getDataInizio() {
		return this.dataInizio;
	}

	public void setDataInizio(Date dataInizio) {
		this.dataInizio = dataInizio;
	}

	public int getDurataCiclo() {
		return this.durataCiclo;
	}

	public void setDurataCiclo(int durataCiclo) {
		this.durataCiclo = durataCiclo;
	}

	public int getNumRipetizCiclo() {
		return this.numRipetizCiclo;
	}

	public void setNumRipetizCiclo(int numRipetizCiclo) {
		this.numRipetizCiclo = numRipetizCiclo;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getUlterioriConsigli() {
		return this.ulterioriConsigli;
	}

	public void setUlterioriConsigli(String ulterioriConsigli) {
		this.ulterioriConsigli = ulterioriConsigli;
	}

	public Set getPersonalizzazionegiornatas() {
		return this.personalizzazionegiornatas;
	}

	public void setPersonalizzazionegiornatas(Set personalizzazionegiornatas) {
		this.personalizzazionegiornatas = personalizzazionegiornatas;
	}

}
