package hibernate;

// Generated 4-feb-2010 12.32.12 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fattura generated by hbm2java
 */
public class Fattura implements java.io.Serializable {

	private Integer idFattura;
	private double importo;
	private Double acconto;
	private Double importoSconto;
	private String note;
	private String descrizione;
	private Date data;
	private Set visitas = new HashSet(0);

	public Fattura() {
	}

	public Fattura(double importo, String descrizione, Date data) {
		this.importo = importo;
		this.descrizione = descrizione;
		this.data = data;
	}

	public Fattura(double importo, Double acconto, Double importoSconto,
			String note, String descrizione, Date data, Set visitas) {
		this.importo = importo;
		this.acconto = acconto;
		this.importoSconto = importoSconto;
		this.note = note;
		this.descrizione = descrizione;
		this.data = data;
		this.visitas = visitas;
	}

	public Integer getIdFattura() {
		return this.idFattura;
	}

	public void setIdFattura(Integer idFattura) {
		this.idFattura = idFattura;
	}

	public double getImporto() {
		return this.importo;
	}

	public void setImporto(double importo) {
		this.importo = importo;
	}

	public Double getAcconto() {
		return this.acconto;
	}

	public void setAcconto(Double acconto) {
		this.acconto = acconto;
	}

	public Double getImportoSconto() {
		return this.importoSconto;
	}

	public void setImportoSconto(Double importoSconto) {
		this.importoSconto = importoSconto;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public Set getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set visitas) {
		this.visitas = visitas;
	}

}
