package hibernate;

// Generated 5-feb-2010 10.52.14 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Funzione generated by hbm2java
 */
public class Funzione implements java.io.Serializable {

	private Integer idFunzione;
	private String descrizione;
	private Set ruolos = new HashSet(0);

	public Funzione() {
	}

	public Funzione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Funzione(String descrizione, Set ruolos) {
		this.descrizione = descrizione;
		this.ruolos = ruolos;
	}

	public Integer getIdFunzione() {
		return this.idFunzione;
	}

	public void setIdFunzione(Integer idFunzione) {
		this.idFunzione = idFunzione;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set getRuolos() {
		return this.ruolos;
	}

	public void setRuolos(Set ruolos) {
		this.ruolos = ruolos;
	}

}
