package hibernate;

// Generated 4-feb-2010 12.32.12 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Ingrediente generated by hbm2java
 */
public class Ingrediente implements java.io.Serializable {

	private Integer idIngrediente;
	private String nome;
	private Set composiziones = new HashSet(0);

	public Ingrediente() {
	}

	public Ingrediente(String nome) {
		this.nome = nome;
	}

	public Ingrediente(String nome, Set composiziones) {
		this.nome = nome;
		this.composiziones = composiziones;
	}

	public Integer getIdIngrediente() {
		return this.idIngrediente;
	}

	public void setIdIngrediente(Integer idIngrediente) {
		this.idIngrediente = idIngrediente;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getComposiziones() {
		return this.composiziones;
	}

	public void setComposiziones(Set composiziones) {
		this.composiziones = composiziones;
	}

}
