package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import common.GenericBean;

/**
 * Intervento generated by hbm2java
 */
public class Intervento extends GenericBean implements java.io.Serializable {

	private InterventoId id;
	private Paziente paziente;
	private Tipologiaintervento tipologiaintervento;
	private Date data;
	private int numero;

	public Intervento() {
	}

	public Intervento(InterventoId id, Paziente paziente,
			Tipologiaintervento tipologiaintervento, int numero) {
		this.id = id;
		this.paziente = paziente;
		this.tipologiaintervento = tipologiaintervento;
		this.numero = numero;
	}

	public Intervento(InterventoId id, Paziente paziente,
			Tipologiaintervento tipologiaintervento, Date data, int numero) {
		this.id = id;
		this.paziente = paziente;
		this.tipologiaintervento = tipologiaintervento;
		this.data = data;
		this.numero = numero;
	}

	public InterventoId getId() {
		return this.id;
	}

	public void setId(InterventoId id) {
		this.id = id;
	}

	public Paziente getPaziente() {
		return this.paziente;
	}

	public void setPaziente(Paziente paziente) {
		this.paziente = paziente;
	}

	public Tipologiaintervento getTipologiaintervento() {
		return this.tipologiaintervento;
	}

	public void setTipologiaintervento(Tipologiaintervento tipologiaintervento) {
		this.tipologiaintervento = tipologiaintervento;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

}
