package hibernate;

// Generated 5-feb-2010 10.52.14 by Hibernate Tools 3.2.4.GA

/**
 * Modalitapastofuori generated by hbm2java
 */
public class Modalitapastofuori implements java.io.Serializable {

	private Integer idModalitaPastoFuori;
	private Abitudinialimentari abitudinialimentari;
	private String luogo;
	private String specificaGiorno;
	private Integer frequenzaGiornaliera;

	public Modalitapastofuori() {
	}

	public Modalitapastofuori(Abitudinialimentari abitudinialimentari,
			String specificaGiorno) {
		this.abitudinialimentari = abitudinialimentari;
		this.specificaGiorno = specificaGiorno;
	}

	public Modalitapastofuori(Abitudinialimentari abitudinialimentari,
			String luogo, String specificaGiorno, Integer frequenzaGiornaliera) {
		this.abitudinialimentari = abitudinialimentari;
		this.luogo = luogo;
		this.specificaGiorno = specificaGiorno;
		this.frequenzaGiornaliera = frequenzaGiornaliera;
	}

	public Integer getIdModalitaPastoFuori() {
		return this.idModalitaPastoFuori;
	}

	public void setIdModalitaPastoFuori(Integer idModalitaPastoFuori) {
		this.idModalitaPastoFuori = idModalitaPastoFuori;
	}

	public Abitudinialimentari getAbitudinialimentari() {
		return this.abitudinialimentari;
	}

	public void setAbitudinialimentari(Abitudinialimentari abitudinialimentari) {
		this.abitudinialimentari = abitudinialimentari;
	}

	public String getLuogo() {
		return this.luogo;
	}

	public void setLuogo(String luogo) {
		this.luogo = luogo;
	}

	public String getSpecificaGiorno() {
		return this.specificaGiorno;
	}

	public void setSpecificaGiorno(String specificaGiorno) {
		this.specificaGiorno = specificaGiorno;
	}

	public Integer getFrequenzaGiornaliera() {
		return this.frequenzaGiornaliera;
	}

	public void setFrequenzaGiornaliera(Integer frequenzaGiornaliera) {
		this.frequenzaGiornaliera = frequenzaGiornaliera;
	}

}
