package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Parametroesame generated by hbm2java
 */
public class Parametroesame implements java.io.Serializable {

	private int idParametroEsame;
	private Esameclinico esameclinico;
	private String nome;
	private String descrizione;
	private String minUomo;
	private String maxUomo;
	private String minDonna;
	private String maxDonna;
	private String minBambino;
	private String maxBambino;
	private Set refertos = new HashSet(0);

	public Parametroesame() {
	}

	public Parametroesame(int idParametroEsame, Esameclinico esameclinico,
			String nome) {
		this.idParametroEsame = idParametroEsame;
		this.esameclinico = esameclinico;
		this.nome = nome;
	}

	public Parametroesame(int idParametroEsame, Esameclinico esameclinico,
			String nome, String descrizione, String minUomo, String maxUomo,
			String minDonna, String maxDonna, String minBambino,
			String maxBambino, Set refertos) {
		this.idParametroEsame = idParametroEsame;
		this.esameclinico = esameclinico;
		this.nome = nome;
		this.descrizione = descrizione;
		this.minUomo = minUomo;
		this.maxUomo = maxUomo;
		this.minDonna = minDonna;
		this.maxDonna = maxDonna;
		this.minBambino = minBambino;
		this.maxBambino = maxBambino;
		this.refertos = refertos;
	}

	public int getIdParametroEsame() {
		return this.idParametroEsame;
	}

	public void setIdParametroEsame(int idParametroEsame) {
		this.idParametroEsame = idParametroEsame;
	}

	public Esameclinico getEsameclinico() {
		return this.esameclinico;
	}

	public void setEsameclinico(Esameclinico esameclinico) {
		this.esameclinico = esameclinico;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getMinUomo() {
		return this.minUomo;
	}

	public void setMinUomo(String minUomo) {
		this.minUomo = minUomo;
	}

	public String getMaxUomo() {
		return this.maxUomo;
	}

	public void setMaxUomo(String maxUomo) {
		this.maxUomo = maxUomo;
	}

	public String getMinDonna() {
		return this.minDonna;
	}

	public void setMinDonna(String minDonna) {
		this.minDonna = minDonna;
	}

	public String getMaxDonna() {
		return this.maxDonna;
	}

	public void setMaxDonna(String maxDonna) {
		this.maxDonna = maxDonna;
	}

	public String getMinBambino() {
		return this.minBambino;
	}

	public void setMinBambino(String minBambino) {
		this.minBambino = minBambino;
	}

	public String getMaxBambino() {
		return this.maxBambino;
	}

	public void setMaxBambino(String maxBambino) {
		this.maxBambino = maxBambino;
	}

	public Set getRefertos() {
		return this.refertos;
	}

	public void setRefertos(Set refertos) {
		this.refertos = refertos;
	}

}
