package hibernate;

// Generated 4-feb-2010 12.32.12 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Parametroantropometrico generated by hbm2java
 */
public class Parametroantropometrico implements java.io.Serializable {

	private Integer idParametroAntropometrico;
	private String nome;
	private String descrizione;
	private Set misuraziones = new HashSet(0);

	public Parametroantropometrico() {
	}

	public Parametroantropometrico(String nome) {
		this.nome = nome;
	}

	public Parametroantropometrico(String nome, String descrizione,
			Set misuraziones) {
		this.nome = nome;
		this.descrizione = descrizione;
		this.misuraziones = misuraziones;
	}

	public Integer getIdParametroAntropometrico() {
		return this.idParametroAntropometrico;
	}

	public void setIdParametroAntropometrico(Integer idParametroAntropometrico) {
		this.idParametroAntropometrico = idParametroAntropometrico;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set getMisuraziones() {
		return this.misuraziones;
	}

	public void setMisuraziones(Set misuraziones) {
		this.misuraziones = misuraziones;
	}

}
