package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

/**
 * Personalizzazionegiornata generated by hbm2java
 */
public class Personalizzazionegiornata implements java.io.Serializable {

	private PersonalizzazionegiornataId id;
	private Dieta dieta;
	private Schemadietetico schemadietetico;

	public Personalizzazionegiornata() {
	}

	public Personalizzazionegiornata(PersonalizzazionegiornataId id,
			Dieta dieta, Schemadietetico schemadietetico) {
		this.id = id;
		this.dieta = dieta;
		this.schemadietetico = schemadietetico;
	}

	public PersonalizzazionegiornataId getId() {
		return this.id;
	}

	public void setId(PersonalizzazionegiornataId id) {
		this.id = id;
	}

	public Dieta getDieta() {
		return this.dieta;
	}

	public void setDieta(Dieta dieta) {
		this.dieta = dieta;
	}

	public Schemadietetico getSchemadietetico() {
		return this.schemadietetico;
	}

	public void setSchemadietetico(Schemadietetico schemadietetico) {
		this.schemadietetico = schemadietetico;
	}

}
