package hibernate;

// Generated 4-feb-2010 12.32.12 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Prescrizione generated by hbm2java
 */
public class Prescrizione implements java.io.Serializable {

	private Integer idPrescrizione;
	private Paziente paziente;
	private Dieta dieta;
	private Date dataInizio;
	private int numRipetizCiclo;
	private String note;

	public Prescrizione() {
	}

	public Prescrizione(Paziente paziente, Dieta dieta, Date dataInizio,
			int numRipetizCiclo) {
		this.paziente = paziente;
		this.dieta = dieta;
		this.dataInizio = dataInizio;
		this.numRipetizCiclo = numRipetizCiclo;
	}

	public Prescrizione(Paziente paziente, Dieta dieta, Date dataInizio,
			int numRipetizCiclo, String note) {
		this.paziente = paziente;
		this.dieta = dieta;
		this.dataInizio = dataInizio;
		this.numRipetizCiclo = numRipetizCiclo;
		this.note = note;
	}

	public Integer getIdPrescrizione() {
		return this.idPrescrizione;
	}

	public void setIdPrescrizione(Integer idPrescrizione) {
		this.idPrescrizione = idPrescrizione;
	}

	public Paziente getPaziente() {
		return this.paziente;
	}

	public void setPaziente(Paziente paziente) {
		this.paziente = paziente;
	}

	public Dieta getDieta() {
		return this.dieta;
	}

	public void setDieta(Dieta dieta) {
		this.dieta = dieta;
	}

	public Date getDataInizio() {
		return this.dataInizio;
	}

	public void setDataInizio(Date dataInizio) {
		this.dataInizio = dataInizio;
	}

	public int getNumRipetizCiclo() {
		return this.numRipetizCiclo;
	}

	public void setNumRipetizCiclo(int numRipetizCiclo) {
		this.numRipetizCiclo = numRipetizCiclo;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
