package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * PrestazioneId generated by hbm2java
 */
public class PrestazioneId implements java.io.Serializable {

	private int idMedico;
	private Date dataTurno;
	private int idTurno;

	public PrestazioneId() {
	}

	public PrestazioneId(int idMedico, Date dataTurno, int idTurno) {
		this.idMedico = idMedico;
		this.dataTurno = dataTurno;
		this.idTurno = idTurno;
	}

	public int getIdMedico() {
		return this.idMedico;
	}

	public void setIdMedico(int idMedico) {
		this.idMedico = idMedico;
	}

	public Date getDataTurno() {
		return this.dataTurno;
	}

	public void setDataTurno(Date dataTurno) {
		this.dataTurno = dataTurno;
	}

	public int getIdTurno() {
		return this.idTurno;
	}

	public void setIdTurno(int idTurno) {
		this.idTurno = idTurno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrestazioneId))
			return false;
		PrestazioneId castOther = (PrestazioneId) other;

		return (this.getIdMedico() == castOther.getIdMedico())
				&& ((this.getDataTurno() == castOther.getDataTurno()) || (this
						.getDataTurno() != null
						&& castOther.getDataTurno() != null && this
						.getDataTurno().equals(castOther.getDataTurno())))
				&& (this.getIdTurno() == castOther.getIdTurno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMedico();
		result = 37 * result
				+ (getDataTurno() == null ? 0 : this.getDataTurno().hashCode());
		result = 37 * result + this.getIdTurno();
		return result;
	}

}
