package hibernate;

// Generated 4-feb-2010 12.32.12 by Hibernate Tools 3.2.4.GA

/**
 * RefertoId generated by hbm2java
 */
public class RefertoId implements java.io.Serializable {

	private int idPaziente;
	private int idParametroEsame;

	public RefertoId() {
	}

	public RefertoId(int idPaziente, int idParametroEsame) {
		this.idPaziente = idPaziente;
		this.idParametroEsame = idParametroEsame;
	}

	public int getIdPaziente() {
		return this.idPaziente;
	}

	public void setIdPaziente(int idPaziente) {
		this.idPaziente = idPaziente;
	}

	public int getIdParametroEsame() {
		return this.idParametroEsame;
	}

	public void setIdParametroEsame(int idParametroEsame) {
		this.idParametroEsame = idParametroEsame;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RefertoId))
			return false;
		RefertoId castOther = (RefertoId) other;

		return (this.getIdPaziente() == castOther.getIdPaziente())
				&& (this.getIdParametroEsame() == castOther
						.getIdParametroEsame());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPaziente();
		result = 37 * result + this.getIdParametroEsame();
		return result;
	}

}
