package hibernate;

// Generated 5-feb-2010 10.52.14 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Rilevamento generated by hbm2java
 */
public class Rilevamento implements java.io.Serializable {

	private Integer idRilevamento;
	private Misurazione misurazione;
	private String valore;
	private Date data;

	public Rilevamento() {
	}

	public Rilevamento(Misurazione misurazione, String valore, Date data) {
		this.misurazione = misurazione;
		this.valore = valore;
		this.data = data;
	}

	public Integer getIdRilevamento() {
		return this.idRilevamento;
	}

	public void setIdRilevamento(Integer idRilevamento) {
		this.idRilevamento = idRilevamento;
	}

	public Misurazione getMisurazione() {
		return this.misurazione;
	}

	public void setMisurazione(Misurazione misurazione) {
		this.misurazione = misurazione;
	}

	public String getValore() {
		return this.valore;
	}

	public void setValore(String valore) {
		this.valore = valore;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
