package hibernate;

// Generated 23-gen-2010 18.34.29 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Risultatoanalisi generated by hbm2java
 */
public class Risultatoanalisi implements java.io.Serializable {

	private Integer idRisultatoAnalisi;
	private Referto referto;
	private String valore;
	private Date data;
	private String note;

	public Risultatoanalisi() {
	}

	public Risultatoanalisi(Referto referto, String valore, Date data) {
		this.referto = referto;
		this.valore = valore;
		this.data = data;
	}

	public Risultatoanalisi(Referto referto, String valore, Date data,
			String note) {
		this.referto = referto;
		this.valore = valore;
		this.data = data;
		this.note = note;
	}

	public Integer getIdRisultatoAnalisi() {
		return this.idRisultatoAnalisi;
	}

	public void setIdRisultatoAnalisi(Integer idRisultatoAnalisi) {
		this.idRisultatoAnalisi = idRisultatoAnalisi;
	}

	public Referto getReferto() {
		return this.referto;
	}

	public void setReferto(Referto referto) {
		this.referto = referto;
	}

	public String getValore() {
		return this.valore;
	}

	public void setValore(String valore) {
		this.valore = valore;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
