package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Tipologiabevanda generated by hbm2java
 */
public class Tipologiabevanda implements java.io.Serializable {

	private Integer idTipologiaBevanda;
	private String nome;
	private String descrizione;
	private Set assunzionebevandes = new HashSet(0);

	public Tipologiabevanda() {
	}

	public Tipologiabevanda(String nome) {
		this.nome = nome;
	}

	public Tipologiabevanda(String nome, String descrizione,
			Set assunzionebevandes) {
		this.nome = nome;
		this.descrizione = descrizione;
		this.assunzionebevandes = assunzionebevandes;
	}

	public Integer getIdTipologiaBevanda() {
		return this.idTipologiaBevanda;
	}

	public void setIdTipologiaBevanda(Integer idTipologiaBevanda) {
		this.idTipologiaBevanda = idTipologiaBevanda;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set getAssunzionebevandes() {
		return this.assunzionebevandes;
	}

	public void setAssunzionebevandes(Set assunzionebevandes) {
		this.assunzionebevandes = assunzionebevandes;
	}

}
