package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import common.GenericBean;

/**
 * Turno generated by hbm2java
 */
public class Turno extends GenericBean implements java.io.Serializable {

	private Integer idTurno;
	private Date oraInizio;
	private Date oraFine;
	private Set prestaziones = new HashSet(0);

	public Turno() {
	}

	public Turno(Date oraInizio, Date oraFine) {
		this.oraInizio = oraInizio;
		this.oraFine = oraFine;
	}

	public Turno(Date oraInizio, Date oraFine, Set prestaziones) {
		this.oraInizio = oraInizio;
		this.oraFine = oraFine;
		this.prestaziones = prestaziones;
	}

	public Integer getIdTurno() {
		return this.idTurno;
	}

	public void setIdTurno(Integer idTurno) {
		this.idTurno = idTurno;
	}

	public Date getOraInizio() {
		return this.oraInizio;
	}

	public void setOraInizio(Date oraInizio) {
		this.oraInizio = oraInizio;
	}

	public Date getOraFine() {
		return this.oraFine;
	}

	public void setOraFine(Date oraFine) {
		this.oraFine = oraFine;
	}

	public Set getPrestaziones() {
		return this.prestaziones;
	}

	public void setPrestaziones(Set prestaziones) {
		this.prestaziones = prestaziones;
	}

}
