insert into ruolo values(null,"Amministratore");
insert into utente values(null,"Admin","admin",1);
insert into funzione values(null,'Registra Utente');
insert into funzione values(null,'Statistiche');
insert into funzione values(null,'Prenota Visita');
insert into funzione values(null,'Registra Visita');
insert into funzione values(null,'Interrogazioni dinamiche');
insert into funzione values(null,'MenuStatisticheHandler');
insert into funzione values(null,'MenuAnamnesi');
insert into funzione values(null,'MenuDinamiche');
insert into funzione values(null,'MenuEsameClinico');
insert into funzione values(null,'MenuGrafici');
insert into funzione values(null,'MenuMedico');
insert into funzione values(null,'MenuParametroAntropometrico');
insert into funzione values(null,'MenuPaziente');
insert into funzione values(null,'MenuPrenotaVisita');
insert into funzione values(null,'MenuRegistraVisita');
insert into funzione values(null,'MenuRegistrazione');
insert into funzione values(null,'MenuRilevazioneParametroAntro');
insert into funzione values(null,'MenuRisultatoAnalisi');
insert into ruolo_funzione values(1,1);
insert into ruolo_funzione values(1,2);
insert into ruolo_funzione values(1,3);
insert into ruolo_funzione values(1,4);
insert into ruolo_funzione values(1,5);
insert into ruolo_funzione values(1,6);
insert into ruolo_funzione values(1,7);
insert into ruolo_funzione values(1,8);
insert into ruolo_funzione values(1,9);
insert into ruolo_funzione values(1,10);
insert into ruolo_funzione values(1,11);
insert into ruolo_funzione values(1,12);
insert into ruolo_funzione values(1,13);
insert into ruolo_funzione values(1,14);
insert into ruolo_funzione values(1,15);
insert into ruolo_funzione values(1,16);
insert into ruolo_funzione values(1,17);
insert into ruolo_funzione values(1,18);