package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

/**
 * Attivitafisica generated by hbm2java
 */
public class Attivitafisica implements java.io.Serializable {

	private Integer idAttivitaFisica;
	private Paziente paziente;
	private String nome;
	private String descrizione;
	private String durata;
	private int frequenzaSettimanale;

	public Attivitafisica() {
	}

	public Attivitafisica(Paziente paziente, String nome,
			int frequenzaSettimanale) {
		this.paziente = paziente;
		this.nome = nome;
		this.frequenzaSettimanale = frequenzaSettimanale;
	}

	public Attivitafisica(Paziente paziente, String nome, String descrizione,
			String durata, int frequenzaSettimanale) {
		this.paziente = paziente;
		this.nome = nome;
		this.descrizione = descrizione;
		this.durata = durata;
		this.frequenzaSettimanale = frequenzaSettimanale;
	}

	public Integer getIdAttivitaFisica() {
		return this.idAttivitaFisica;
	}

	public void setIdAttivitaFisica(Integer idAttivitaFisica) {
		this.idAttivitaFisica = idAttivitaFisica;
	}

	public Paziente getPaziente() {
		return this.paziente;
	}

	public void setPaziente(Paziente paziente) {
		this.paziente = paziente;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getDurata() {
		return this.durata;
	}

	public void setDurata(String durata) {
		this.durata = durata;
	}

	public int getFrequenzaSettimanale() {
		return this.frequenzaSettimanale;
	}

	public void setFrequenzaSettimanale(int frequenzaSettimanale) {
		this.frequenzaSettimanale = frequenzaSettimanale;
	}

}
