package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

/**
 * CostituzioneId generated by hbm2java
 */
public class CostituzioneId implements java.io.Serializable {

	private int idSchemaDietetico;
	private int idAlimento;
	private int idPasto;

	public CostituzioneId() {
	}

	public CostituzioneId(int idSchemaDietetico, int idAlimento, int idPasto) {
		this.idSchemaDietetico = idSchemaDietetico;
		this.idAlimento = idAlimento;
		this.idPasto = idPasto;
	}

	public int getIdSchemaDietetico() {
		return this.idSchemaDietetico;
	}

	public void setIdSchemaDietetico(int idSchemaDietetico) {
		this.idSchemaDietetico = idSchemaDietetico;
	}

	public int getIdAlimento() {
		return this.idAlimento;
	}

	public void setIdAlimento(int idAlimento) {
		this.idAlimento = idAlimento;
	}

	public int getIdPasto() {
		return this.idPasto;
	}

	public void setIdPasto(int idPasto) {
		this.idPasto = idPasto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CostituzioneId))
			return false;
		CostituzioneId castOther = (CostituzioneId) other;

		return (this.getIdSchemaDietetico() == castOther.getIdSchemaDietetico())
				&& (this.getIdAlimento() == castOther.getIdAlimento())
				&& (this.getIdPasto() == castOther.getIdPasto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSchemaDietetico();
		result = 37 * result + this.getIdAlimento();
		result = 37 * result + this.getIdPasto();
		return result;
	}

}
