package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Esameclinico generated by hbm2java
 */
public class Esameclinico implements java.io.Serializable {

	private Integer idEsameClinico;
	private String nome;
	private String descrizione;
	private Set parametroesames = new HashSet(0);

	public Esameclinico() {
	}

	public Esameclinico(String nome) {
		this.nome = nome;
	}

	public Esameclinico(String nome, String descrizione, Set parametroesames) {
		this.nome = nome;
		this.descrizione = descrizione;
		this.parametroesames = parametroesames;
	}

	public Integer getIdEsameClinico() {
		return this.idEsameClinico;
	}

	public void setIdEsameClinico(Integer idEsameClinico) {
		this.idEsameClinico = idEsameClinico;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set getParametroesames() {
		return this.parametroesames;
	}

	public void setParametroesames(Set parametroesames) {
		this.parametroesames = parametroesames;
	}

}
