package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

/**
 * Farmacoassunto generated by hbm2java
 */
public class Farmacoassunto implements java.io.Serializable {

	private Integer idFarmacoAssunto;
	private Paziente paziente;
	private String nome;
	private String descrizione;
	private String dose;
	private String frequenza;
	private String principiAttivi;

	public Farmacoassunto() {
	}

	public Farmacoassunto(Paziente paziente, String nome, String dose,
			String frequenza) {
		this.paziente = paziente;
		this.nome = nome;
		this.dose = dose;
		this.frequenza = frequenza;
	}

	public Farmacoassunto(Paziente paziente, String nome, String descrizione,
			String dose, String frequenza, String principiAttivi) {
		this.paziente = paziente;
		this.nome = nome;
		this.descrizione = descrizione;
		this.dose = dose;
		this.frequenza = frequenza;
		this.principiAttivi = principiAttivi;
	}

	public Integer getIdFarmacoAssunto() {
		return this.idFarmacoAssunto;
	}

	public void setIdFarmacoAssunto(Integer idFarmacoAssunto) {
		this.idFarmacoAssunto = idFarmacoAssunto;
	}

	public Paziente getPaziente() {
		return this.paziente;
	}

	public void setPaziente(Paziente paziente) {
		this.paziente = paziente;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getDose() {
		return this.dose;
	}

	public void setDose(String dose) {
		this.dose = dose;
	}

	public String getFrequenza() {
		return this.frequenza;
	}

	public void setFrequenza(String frequenza) {
		this.frequenza = frequenza;
	}

	public String getPrincipiAttivi() {
		return this.principiAttivi;
	}

	public void setPrincipiAttivi(String principiAttivi) {
		this.principiAttivi = principiAttivi;
	}

}
