package hibernate;

// Generated 4-feb-2010 12.32.12 by Hibernate Tools 3.2.4.GA

/**
 * InterventoId generated by hbm2java
 */
public class InterventoId implements java.io.Serializable {

	private int idPaziente;
	private int idTipologiaIntervento;

	public InterventoId() {
	}

	public InterventoId(int idPaziente, int idTipologiaIntervento) {
		this.idPaziente = idPaziente;
		this.idTipologiaIntervento = idTipologiaIntervento;
	}

	public int getIdPaziente() {
		return this.idPaziente;
	}

	public void setIdPaziente(int idPaziente) {
		this.idPaziente = idPaziente;
	}

	public int getIdTipologiaIntervento() {
		return this.idTipologiaIntervento;
	}

	public void setIdTipologiaIntervento(int idTipologiaIntervento) {
		this.idTipologiaIntervento = idTipologiaIntervento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InterventoId))
			return false;
		InterventoId castOther = (InterventoId) other;

		return (this.getIdPaziente() == castOther.getIdPaziente())
				&& (this.getIdTipologiaIntervento() == castOther
						.getIdTipologiaIntervento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPaziente();
		result = 37 * result + this.getIdTipologiaIntervento();
		return result;
	}

}
