package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Malattia generated by hbm2java
 */
public class Malattia implements java.io.Serializable {

	private Integer idMalattia;
	private Tipologiadietaspeciale tipologiadietaspeciale;
	private String patologia;
	private Boolean malattiaEreditaria;
	private Set pazientes = new HashSet(0);

	public Malattia() {
	}

	public Malattia(Tipologiadietaspeciale tipologiadietaspeciale,
			String patologia, Boolean malattiaEreditaria, Set pazientes) {
		this.tipologiadietaspeciale = tipologiadietaspeciale;
		this.patologia = patologia;
		this.malattiaEreditaria = malattiaEreditaria;
		this.pazientes = pazientes;
	}

	public Integer getIdMalattia() {
		return this.idMalattia;
	}

	public void setIdMalattia(Integer idMalattia) {
		this.idMalattia = idMalattia;
	}

	public Tipologiadietaspeciale getTipologiadietaspeciale() {
		return this.tipologiadietaspeciale;
	}

	public void setTipologiadietaspeciale(
			Tipologiadietaspeciale tipologiadietaspeciale) {
		this.tipologiadietaspeciale = tipologiadietaspeciale;
	}

	public String getPatologia() {
		return this.patologia;
	}

	public void setPatologia(String patologia) {
		this.patologia = patologia;
	}

	public Boolean getMalattiaEreditaria() {
		return this.malattiaEreditaria;
	}

	public void setMalattiaEreditaria(Boolean malattiaEreditaria) {
		this.malattiaEreditaria = malattiaEreditaria;
	}

	public Set getPazientes() {
		return this.pazientes;
	}

	public void setPazientes(Set pazientes) {
		this.pazientes = pazientes;
	}

}
