package hibernate;

// Generated 5-feb-2010 10.52.14 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico implements java.io.Serializable {

	private Integer idMedico;
	private String codiceFiscale;
	private String cognome;
	private String nome;
	private Date dataNascita;
	private char sesso;
	private String indirizzo;
	private String citta;
	private String cap;
	private String provincia;
	private String specializzazione;
	private String telefono1;
	private String telefono2;
	private String email;
	private Set prestaziones = new HashSet(0);
	private Set visitas = new HashSet(0);

	public Medico() {
	}

	public Medico(String codiceFiscale, String cognome, String nome,
			Date dataNascita, char sesso, String specializzazione) {
		this.codiceFiscale = codiceFiscale;
		this.cognome = cognome;
		this.nome = nome;
		this.dataNascita = dataNascita;
		this.sesso = sesso;
		this.specializzazione = specializzazione;
	}

	public Medico(String codiceFiscale, String cognome, String nome,
			Date dataNascita, char sesso, String indirizzo, String citta,
			String cap, String provincia, String specializzazione,
			String telefono1, String telefono2, String email, Set prestaziones,
			Set visitas) {
		this.codiceFiscale = codiceFiscale;
		this.cognome = cognome;
		this.nome = nome;
		this.dataNascita = dataNascita;
		this.sesso = sesso;
		this.indirizzo = indirizzo;
		this.citta = citta;
		this.cap = cap;
		this.provincia = provincia;
		this.specializzazione = specializzazione;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.email = email;
		this.prestaziones = prestaziones;
		this.visitas = visitas;
	}

	public Integer getIdMedico() {
		return this.idMedico;
	}

	public void setIdMedico(Integer idMedico) {
		this.idMedico = idMedico;
	}

	public String getCodiceFiscale() {
		return this.codiceFiscale;
	}

	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Date getDataNascita() {
		return this.dataNascita;
	}

	public void setDataNascita(Date dataNascita) {
		this.dataNascita = dataNascita;
	}

	public char getSesso() {
		return this.sesso;
	}

	public void setSesso(char sesso) {
		this.sesso = sesso;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getCitta() {
		return this.citta;
	}

	public void setCitta(String citta) {
		this.citta = citta;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getSpecializzazione() {
		return this.specializzazione;
	}

	public void setSpecializzazione(String specializzazione) {
		this.specializzazione = specializzazione;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getPrestaziones() {
		return this.prestaziones;
	}

	public void setPrestaziones(Set prestaziones) {
		this.prestaziones = prestaziones;
	}

	public Set getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set visitas) {
		this.visitas = visitas;
	}

}
