package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import common.GenericBean;

/**
 * Paziente generated by hbm2java
 */
public class Paziente extends GenericBean implements java.io.Serializable {

	private Integer idPaziente;
	private String codiceFiscale;
	private String cognome;
	private String nome;
	private Date dataNascita;
	private char sesso;
	private String indirizzo;
	private String citta;
	private String cap;
	private String provincia;
	private String professione;
	private String telefono1;
	private String telefono2;
	private String email;
	private String numTesseraSanitaria;
	private String note;
	private Set attivitafisicas = new HashSet(0);
	private Set interventos = new HashSet(0);
	private Set intolleranzaallergias = new HashSet(0);
	private Set farmacoassuntos = new HashSet(0);
	private Set malattias = new HashSet(0);
	private Set prenotaziones = new HashSet(0);
	private Set abitudinialimentaris = new HashSet(0);
	private Set refertos = new HashSet(0);
	private Set misuraziones = new HashSet(0);
	private Set dietas = new HashSet(0);

	public Paziente() {
	}

	public Paziente(String codiceFiscale, String cognome, String nome,
			Date dataNascita, char sesso) {
		this.codiceFiscale = codiceFiscale;
		this.cognome = cognome;
		this.nome = nome;
		this.dataNascita = dataNascita;
		this.sesso = sesso;
	}

	public Paziente(String codiceFiscale, String cognome, String nome,
			Date dataNascita, char sesso, String indirizzo, String citta,
			String cap, String provincia, String professione, String telefono1,
			String telefono2, String email, String numTesseraSanitaria,
			String note, Set attivitafisicas, Set interventos,
			Set intolleranzaallergias, Set farmacoassuntos, Set malattias,
			Set prenotaziones, Set abitudinialimentaris, Set refertos,
			Set misuraziones, Set dietas) {
		this.codiceFiscale = codiceFiscale;
		this.cognome = cognome;
		this.nome = nome;
		this.dataNascita = dataNascita;
		this.sesso = sesso;
		this.indirizzo = indirizzo;
		this.citta = citta;
		this.cap = cap;
		this.provincia = provincia;
		this.professione = professione;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.email = email;
		this.numTesseraSanitaria = numTesseraSanitaria;
		this.note = note;
		this.attivitafisicas = attivitafisicas;
		this.interventos = interventos;
		this.intolleranzaallergias = intolleranzaallergias;
		this.farmacoassuntos = farmacoassuntos;
		this.malattias = malattias;
		this.prenotaziones = prenotaziones;
		this.abitudinialimentaris = abitudinialimentaris;
		this.refertos = refertos;
		this.misuraziones = misuraziones;
		this.dietas = dietas;
	}

	public Integer getIdPaziente() {
		return this.idPaziente;
	}

	public void setIdPaziente(Integer idPaziente) {
		this.idPaziente = idPaziente;
	}

	public String getCodiceFiscale() {
		return this.codiceFiscale;
	}

	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Date getDataNascita() {
		return this.dataNascita;
	}

	public void setDataNascita(Date dataNascita) {
		this.dataNascita = dataNascita;
	}

	public char getSesso() {
		return this.sesso;
	}

	public void setSesso(char sesso) {
		this.sesso = sesso;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getCitta() {
		return this.citta;
	}

	public void setCitta(String citta) {
		this.citta = citta;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getProfessione() {
		return this.professione;
	}

	public void setProfessione(String professione) {
		this.professione = professione;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNumTesseraSanitaria() {
		return this.numTesseraSanitaria;
	}

	public void setNumTesseraSanitaria(String numTesseraSanitaria) {
		this.numTesseraSanitaria = numTesseraSanitaria;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set getAttivitafisicas() {
		return this.attivitafisicas;
	}

	public void setAttivitafisicas(Set attivitafisicas) {
		this.attivitafisicas = attivitafisicas;
	}

	public Set getInterventos() {
		return this.interventos;
	}

	public void setInterventos(Set interventos) {
		this.interventos = interventos;
	}

	public Set getIntolleranzaallergias() {
		return this.intolleranzaallergias;
	}

	public void setIntolleranzaallergias(Set intolleranzaallergias) {
		this.intolleranzaallergias = intolleranzaallergias;
	}

	public Set getFarmacoassuntos() {
		return this.farmacoassuntos;
	}

	public void setFarmacoassuntos(Set farmacoassuntos) {
		this.farmacoassuntos = farmacoassuntos;
	}

	public Set getMalattias() {
		return this.malattias;
	}

	public void setMalattias(Set malattias) {
		this.malattias = malattias;
	}

	public Set getPrenotaziones() {
		return this.prenotaziones;
	}

	public void setPrenotaziones(Set prenotaziones) {
		this.prenotaziones = prenotaziones;
	}

	public Set getAbitudinialimentaris() {
		return this.abitudinialimentaris;
	}

	public void setAbitudinialimentaris(Set abitudinialimentaris) {
		this.abitudinialimentaris = abitudinialimentaris;
	}

	public Set getRefertos() {
		return this.refertos;
	}

	public void setRefertos(Set refertos) {
		this.refertos = refertos;
	}

	public Set getMisuraziones() {
		return this.misuraziones;
	}

	public void setMisuraziones(Set misuraziones) {
		this.misuraziones = misuraziones;
	}

	public Set getDietas() {
		return this.dietas;
	}

	public void setDietas(Set dietas) {
		this.dietas = dietas;
	}

}
