package hibernate;

// Generated 5-feb-2010 10.52.14 by Hibernate Tools 3.2.4.GA

/**
 * PersonalizzazionegiornataId generated by hbm2java
 */
public class PersonalizzazionegiornataId implements java.io.Serializable {

	private int idSchemaDietetico;
	private int idDieta;
	private int giornoCiclo;

	public PersonalizzazionegiornataId() {
	}

	public PersonalizzazionegiornataId(int idSchemaDietetico, int idDieta,
			int giornoCiclo) {
		this.idSchemaDietetico = idSchemaDietetico;
		this.idDieta = idDieta;
		this.giornoCiclo = giornoCiclo;
	}

	public int getIdSchemaDietetico() {
		return this.idSchemaDietetico;
	}

	public void setIdSchemaDietetico(int idSchemaDietetico) {
		this.idSchemaDietetico = idSchemaDietetico;
	}

	public int getIdDieta() {
		return this.idDieta;
	}

	public void setIdDieta(int idDieta) {
		this.idDieta = idDieta;
	}

	public int getGiornoCiclo() {
		return this.giornoCiclo;
	}

	public void setGiornoCiclo(int giornoCiclo) {
		this.giornoCiclo = giornoCiclo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonalizzazionegiornataId))
			return false;
		PersonalizzazionegiornataId castOther = (PersonalizzazionegiornataId) other;

		return (this.getIdSchemaDietetico() == castOther.getIdSchemaDietetico())
				&& (this.getIdDieta() == castOther.getIdDieta())
				&& (this.getGiornoCiclo() == castOther.getGiornoCiclo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSchemaDietetico();
		result = 37 * result + this.getIdDieta();
		result = 37 * result + this.getGiornoCiclo();
		return result;
	}

}
