package hibernate;

// Generated 5-feb-2010 10.52.14 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Prenotazione generated by hbm2java
 */
public class Prenotazione implements java.io.Serializable {

	private Integer idPrenotazione;
	private Tipologiavisita tipologiavisita;
	private Paziente paziente;
	private Date dataOra;
	private String note;
	private Set visitas = new HashSet(0);

	public Prenotazione() {
	}

	public Prenotazione(Tipologiavisita tipologiavisita, Paziente paziente,
			Date dataOra) {
		this.tipologiavisita = tipologiavisita;
		this.paziente = paziente;
		this.dataOra = dataOra;
	}

	public Prenotazione(Tipologiavisita tipologiavisita, Paziente paziente,
			Date dataOra, String note, Set visitas) {
		this.tipologiavisita = tipologiavisita;
		this.paziente = paziente;
		this.dataOra = dataOra;
		this.note = note;
		this.visitas = visitas;
	}

	public Integer getIdPrenotazione() {
		return this.idPrenotazione;
	}

	public void setIdPrenotazione(Integer idPrenotazione) {
		this.idPrenotazione = idPrenotazione;
	}

	public Tipologiavisita getTipologiavisita() {
		return this.tipologiavisita;
	}

	public void setTipologiavisita(Tipologiavisita tipologiavisita) {
		this.tipologiavisita = tipologiavisita;
	}

	public Paziente getPaziente() {
		return this.paziente;
	}

	public void setPaziente(Paziente paziente) {
		this.paziente = paziente;
	}

	public Date getDataOra() {
		return this.dataOra;
	}

	public void setDataOra(Date dataOra) {
		this.dataOra = dataOra;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set visitas) {
		this.visitas = visitas;
	}

}
