package hibernate;

// Generated 14-gen-2010 20.26.42 by Hibernate Tools 3.2.4.GA

/**
 * Prestazione generated by hbm2java
 */
public class Prestazione implements java.io.Serializable {

	private PrestazioneId id;
	private Turno turno;
	private Medico medico;

	public Prestazione() {
	}

	public Prestazione(PrestazioneId id, Turno turno, Medico medico) {
		this.id = id;
		this.turno = turno;
		this.medico = medico;
	}

	public PrestazioneId getId() {
		return this.id;
	}

	public void setId(PrestazioneId id) {
		this.id = id;
	}

	public Turno getTurno() {
		return this.turno;
	}

	public void setTurno(Turno turno) {
		this.turno = turno;
	}

	public Medico getMedico() {
		return this.medico;
	}

	public void setMedico(Medico medico) {
		this.medico = medico;
	}

}
