package hibernate;

// Generated 5-feb-2010 10.52.14 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Ruolo generated by hbm2java
 */
public class Ruolo implements java.io.Serializable {

	private Integer idRuolo;
	private String descrizione;
	private Set utentes = new HashSet(0);
	private Set funziones = new HashSet(0);

	public Ruolo() {
	}

	public Ruolo(String descrizione) {
		this.descrizione = descrizione;
	}

	public Ruolo(String descrizione, Set utentes, Set funziones) {
		this.descrizione = descrizione;
		this.utentes = utentes;
		this.funziones = funziones;
	}

	public Integer getIdRuolo() {
		return this.idRuolo;
	}

	public void setIdRuolo(Integer idRuolo) {
		this.idRuolo = idRuolo;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set getUtentes() {
		return this.utentes;
	}

	public void setUtentes(Set utentes) {
		this.utentes = utentes;
	}

	public Set getFunziones() {
		return this.funziones;
	}

	public void setFunziones(Set funziones) {
		this.funziones = funziones;
	}

}
