package hibernate;

// Generated 5-feb-2010 10.52.14 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Tipologiaintervento generated by hbm2java
 */
public class Tipologiaintervento implements java.io.Serializable {

	private Integer idTipologiaIntervento;
	private String nome;
	private String descrizione;
	private String localizzazione;
	private Set interventos = new HashSet(0);

	public Tipologiaintervento() {
	}

	public Tipologiaintervento(String nome, String localizzazione) {
		this.nome = nome;
		this.localizzazione = localizzazione;
	}

	public Tipologiaintervento(String nome, String descrizione,
			String localizzazione, Set interventos) {
		this.nome = nome;
		this.descrizione = descrizione;
		this.localizzazione = localizzazione;
		this.interventos = interventos;
	}

	public Integer getIdTipologiaIntervento() {
		return this.idTipologiaIntervento;
	}

	public void setIdTipologiaIntervento(Integer idTipologiaIntervento) {
		this.idTipologiaIntervento = idTipologiaIntervento;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getLocalizzazione() {
		return this.localizzazione;
	}

	public void setLocalizzazione(String localizzazione) {
		this.localizzazione = localizzazione;
	}

	public Set getInterventos() {
		return this.interventos;
	}

	public void setInterventos(Set interventos) {
		this.interventos = interventos;
	}

}
