package hibernate;

// Generated 5-feb-2010 10.52.14 by Hibernate Tools 3.2.4.GA

/**
 * Utente generated by hbm2java
 */
public class Utente implements java.io.Serializable {

	private Integer idUtente;
	private Ruolo ruolo;
	private String nomeUtente;
	private String password;

	public Utente() {
	}

	public Utente(Ruolo ruolo, String nomeUtente, String password) {
		this.ruolo = ruolo;
		this.nomeUtente = nomeUtente;
		this.password = password;
	}

	public Integer getIdUtente() {
		return this.idUtente;
	}

	public void setIdUtente(Integer idUtente) {
		this.idUtente = idUtente;
	}

	public Ruolo getRuolo() {
		return this.ruolo;
	}

	public void setRuolo(Ruolo ruolo) {
		this.ruolo = ruolo;
	}

	public String getNomeUtente() {
		return this.nomeUtente;
	}

	public void setNomeUtente(String nomeUtente) {
		this.nomeUtente = nomeUtente;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
